### ISSUE TITLE
Add ability to use secrets

### ISSUE THREAD

**Issue by katherine-boost** [halkeye-helm-charts/vouch#1]
Hi there, thanks so much for providing this Helm chart!

I have a feature request: it would be awesome if there was some way to pass `SealedSecrets` to the Vouch helm chart, so that I can take mine out of plain text. Specifically,

* `config.vouch.jwt.secret` - https://github.com/halkeye-helm-charts/vouch/blob/master/values.yaml#L59
* `config.oauth.client_id` & `.client_secret` - https://github.com/halkeye-helm-charts/vouch/blob/master/values.yaml#L66:L67

e.g. how the [MongoDB Replica Set Helm Chart](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset#configuration) implements `auth.existingKeySecret`, `auth.existingMetricsSecret`, and `auth.existingAdminSecret`.

I could maybe take a stab at a PR in a couple of weeks, if you're open to that.

Cheers!

**Comment by halkeye** [comment]
Always open to PRs. I'll see what I can do though. Existing is probably doable

**Comment by bnfinet** [comment]
Let me know if there's anything I can do to help.

FYI env var config is about to drop later the week.  Not sure if that would
be helpful in this situation.

**Comment by halkeye** [comment]
I use helm secrets (sops) myself, so not a high priority for me, but it shouldn't be that hard to make all of https://github.com/halkeye-helm-charts/vouch/blob/master/templates/configmap.yaml a secret (i've learned a lot since this chart was made), and then if existingSecretName is set, just let you use existingSecretName instead of the chart populating it.

Just that new terraria dropped and I'm easily distracted :)

**Comment by bnfinet** [comment]
FYI - @bgehman offered this writeup including some details of his helm chart implementation using `Secret` instead of `ConfigMap`
https://github.com/vouch/vouch-proxy/pull/263#issuecomment-628297832

**Comment by bgehman** [comment]
@halkeye I don't have much experience with `SealedSecrets` (what OP is asking for), but I can submit a PR for moving the existing `ConfigMap` to `Secret` (very minor changes needed).

**Comment by halkeye** [comment]
Yea i'm not going to support sealedsecrets directly, cause its a custom resource descriptor that will break on some installs, but migrate from configmap => secret (👍 ) and supporting existingSecretName (👍) should handle the requested case

**Comment by halkeye** [comment]
This should be fixed via 92aeca90d4491a56ea16ed0bafec4b6a61b7363a

I added existingSecretName if you want to completely override the secret the chart generates

**Comment by halkeye** [comment]
closed via #
