### ISSUE TITLE
Updating from version 0.3.1 to version 1.0.0 fails with conflict error

### ISSUE THREAD

**Issue by punkle** [halkeye-helm-charts/vouch#7]
Updating from version 0.3.1 to version 1.0.0 of the helm chart gives me the following error.

```Unable to continue with update: existing resource conflict: namespace: default, name: default-vouch, existing_kind: networking.k8s.io/v1beta1, Kind=Ingress, new_kind: networking.k8s.io/v1beta1, Kind=Ingress```

I am happy to provide more information or help fix this if I can.

**Comment by halkeye** [comment]
Easiest solution is probably to delete your existing ingress, or use --force
I'm not sure why they wouldn't match and do a replacement

if your unwilling to do that, maybe provide a helm diff if you have that plugin

**Comment by punkle** [comment]
I dont have helm diff. I think it's probably acceptable to delete the ingress manually. Thanks for the help. :)
